title: Insert Site Title
email: your-email@example.com
github_username:  davidewarren

name: Insert Site Title

repos:
- name: federalist-guide-template
  description: Main repository
  url: https://github.com/davidewarren/federalist-guide-template

collections:
  pages:
    output: true
    permalink: /:path/

docs_list_title: ACME Documentation
docs:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
 
 # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
